sudo: false
language: android
env:
  global:
   - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-27

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26

    # Emulator Management: Create, Start and Wait
  before_script:
      - echo no | android create avd --force -n test -t android-27 --abi armeabi-v7a
      - emulator -avd test -no-skin -no-audio -no-window -gpu off &
      - android-wait-for-emulator
      - adb shell input keyevent 82 &

  script:
      - echo $ADB_INSTALL_TIMEOUT
      - android list target
      - ./gradlew connectedAndroidTest